// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://diczmegfavgyxftwmnog.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRpY3ptZWdmYXZneXhmdHdtbm9nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE2MjIxODUsImV4cCI6MjA3NzE5ODE4NX0.osryjSmmcGj3HmaET0IWBgZa1h13EwrQvBabAt4hMcU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);